title: Ghyslain Gaillard
url: "http://ghyslain.me"
baseurl: "/"
keywords: "data science, data scientist, machine learning, london, junior, graduate, spark, scala, ecole centrale lyon, ghyslain gaillard, blog, personal website"

markdown: kramdown

tracking_id: UA-89100132-1

sass:
    style: compressed
    sass_dir: _sass

collections:
  books:
    output: false
