title: "Ghyslain Gaillard"
url: "https://ghyslain.me"
baseurl: "/"
keywords: "data product management, product management, data science, data scientist, machine learning, london, london indie hackers, indiehackers, ihlondon, indie london, indie entrepreneurs, bootstrapper, venture capital, vc, fundraising, startups, ghyslain gaillard"
author: "Ghyslain Gaillard"

favicon: true
favicon_location: "./favicon.png"

markdown: kramdown

tracking_id: "UA-89100132-1"

sass:
    style: compressed
    sass_dir: _sass

collections:
  books:
    output: false
