title: "Ghyslain Gaillard"
url: "https://ghyslain.me"
baseurl: "/"
keywords: "data science, data scientist, machine learning, london, london indie hackers, indiehackers, ihlondon, bootstrapper, venture capital, vc, fundraising, ecole centrale lyon, ghyslain gaillard"
author: "Ghyslain Gaillard"

markdown: kramdown

tracking_id: "UA-89100132-1"

sass:
    style: compressed
    sass_dir: _sass

collections:
  books:
    output: false
